# When a pull request is created, this run checks on the changes to be merged

name: Pull request ci build

on:
  push:
    branches:
      - "new-dev-env"
  #  pull_request:
  #    branches: ["main"]

  miniconda:
    name: Miniconda ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          environment-file: environment.yml
          auto-activate-base: false
    
      - name: Install Dependencies
        run: pip install .
