# When a pull request is created, this run checks on the changes to be merged

name: Pull request ci build

on:
  push:
    branches: ["new-dev-env"]
  #  pull_request:
  #    branches: ["main"]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest] # ["windows-latest", "ubuntu-latest"]

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          environment-file: environment.yml
          activate-environment: bci
    
      - name: Install Dependencies
        run: pip install .

